name: MiniCashShigenAssist
version: '1.0-SNAPSHOT'
main: MiniCash.miniCashShigenAssist.MiniCashShigenAssist
api-version: '1.21'

commands:
  minerassist:
    usage: "/minerassist"
    description: §cMinerassistプラグインのメインコマンド
    default: op

    permission: minicashshigenassist.commands.minerassist
  assist:
    usage: "/assist"
    desctiption: §c採掘勢の助けになる機能を提供します
    default: op
    permission: minicashshigenassist.commands.assist
